# Generated by Django 4.2.4 on 2023-08-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_alter_ativo_limite_inferior_tunnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='setor',
            field=models.CharField(choices=[('CONSUMO_CICLICO', 'Consumo Cíclico'), ('CONSUMO_NAO_CICLICO', 'Consumo não Cíclico'), ('UTILIDADE_PUBLICA', 'Utilidade Pública'), ('BENS_INDUSTRIAIS', 'Bens Industriais'), ('MATERIAIS_BASICOS', 'Materiais Básicos'), ('FINANCEIRO_E_OUTROS', 'Financeiro e Outros'), ('TECNOLOGIA_DA_INFORMACAO', 'Tecnologia da Informação'), ('SAUDE', 'Saúde'), ('PETROLEO_GAS_E_BIOCOMBUSTIVEIS', 'Petróleo, Gás e Biocombustíveis'), ('COMUNICACOES', 'Comunicações')], default='', help_text='setor ao qual o ativo pertence', max_length=100),
        ),
    ]
