# Generated by Django 4.2.4 on 2023-08-06 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_ativo_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Data e hora da última atualização do preço', null=True),
        ),
    ]
