# Generated by Django 4.2.4 on 2023-08-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_alter_ativo_ultima_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='limite_inferior_tunnel',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='limite_superior_tunnel',
        ),
        migrations.AddField(
            model_name='ativo',
            name='limite_inferior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='limite_superior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
