# Generated by Django 4.2.4 on 2023-08-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0005_remove_ativo_limite_inferior_tunnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='setor',
            field=models.CharField(choices=[('CONSUMER_CYCLICAL', 'Consumo Cíclico'), ('CONSUMER_DEFENSIVE', 'Consumo não Cíclico'), ('UTILITIES', 'Utilidade Pública'), ('INDUSTRIALS', 'Bens Industriais'), ('BASIC_MATERIALS', 'Materiais Básicos'), ('FINANCIAL_SERVICES', 'Financeiro e Outros'), ('TECHNOLOGY', 'Tecnologia da Informação'), ('HEALTHCARE', 'Saúde'), ('ENERGY', 'Petróleo, Gás e Biocombustíveis'), ('COMMUNICATION_SERVICES', 'Comunicações')], default='', help_text='setor ao qual o ativo pertence', max_length=100),
        ),
    ]
