# Generated by Django 4.2.4 on 2023-08-07 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoramento', '0006_alter_ativo_preco_atual_alter_ativo_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='caminho_imagem',
        ),
        migrations.AddField(
            model_name='ativo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='setor',
            field=models.CharField(choices=[('CONSUMER_CYCLICAL', 'Consumo Cíclico'), ('CONSUMER_DEFENSIVE', 'Consumo não Cíclico'), ('UTILITIES', 'Utilidade Pública'), ('INDUSTRIALS', 'Bens Industriais'), ('BASIC_MATERIALS', 'Materiais Básicos'), ('FINANCIAL_SERVICES', 'Financeiro e Outros'), ('TECHNOLOGY', 'Tecnologia da Informação'), ('HEALTHCARE', 'Saúde'), ('ENERGY', 'Petróleo, Gás e Biocombustíveis'), ('COMMUNICATION_SERVICES', 'Comunicações'), ('REAL_ESTATE', 'Imóveis')], default='', help_text='setor ao qual o ativo pertence', max_length=100),
        ),
    ]
