# Generated by Django 4.2.4 on 2023-08-07 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoramento', '0007_remove_ativo_caminho_imagem_ativo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
