# Generated by Django 4.2.4 on 2023-08-07 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0008_alter_ativo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Data e hora da última atualização do preço', null=True),
        ),
    ]
