# Generated by Django 4.2.4 on 2023-08-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0009_alter_ativo_ultima_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='variacao_preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
