# Generated by Django 4.2.4 on 2023-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='limite_inferior_tunnel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite inferior do túnel de preço', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='limite_superior_tunnel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Limite superior do túnel de preço', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='periodicidade_checagem',
            field=models.PositiveIntegerField(blank=True, help_text='Periodicidade da checagem em minutos', null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='preco_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
